@BOMA.RTR.Api_HostAddress = http://localhost:5133

GET {{BOMA.RTR.Api_HostAddress}}/weatherforecast/
Accept: application/json

GET {{BOMA.RTR.Api_HostAddress}}/entryExitTimes/
Accept: application/json

###
